name: Build APK
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FileRisk-APK
          path: ${{ steps.buildozer.outputs.filename }}
